### ISSUE TITLE
Custom help does not work in a certain way.

### ISSUE THREAD

**Issue by quillincn** [SkinsRestorer/SkinsRestorerX#1406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

In case when custom help is enabled and im using ``/skin help``, it is giving me the correct message which I set in the ``SkinsRestorer/config.yml``, but when im using command to which I did not have permission access, then i get default message from the ``SkinsRestorer/locales/custom/locale.json``.

![изображение](https://github.com/SkinsRestorer/SkinsRestorerX/assets/18488764/3383c1fa-a52b-4a10-ad1e-fc105d8abedb)

### How can we reproduce what you got?

1. Set custom help as a true.
```
    customHelp:
        # Override the automatically generated translated help message with a custom one.
        # This is useful if you want to have a custom help message for your server.
        # This only affects the base help message when running /skin with no parameters, not the error/subcommand help messages.
        enabled: true
        # The custom help message to send to the player when running /skin with no parameters.
        message: 
        - <red>Custom help test message
```
2. Use ``/skin``, then you will see the custom help message.
3. Restrict use of any plugin command in permissions. In my case, I restricted the ``/skin update`` command with permission ``skinsrestorer.command.update`` set to ``false``.
4. Use the restricted command in the chat (``/skin update``), and after that you will get the help message from the locale.json file instead of the custom message from the ``config.yml`` file.

### Server/Error Logs

https://bin.birdflop.com/hogimuqije.makefile

### Minecraft implementation

```markdown
Proxy: no
Backend: Paper version git-Paper-249 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 996d529)
```

### What client are you using?

Modrinth App

### SkinsRestorer Version

15.0.3

### List of plugins

AntiPopup, AuthMe, CommandBlocker, Essentials, EssentialsChat, EssentialsSpawn, GSit, InventoryRollbackPlus, InvSeePlusPlus, LuckPerms, MiniMOTD, MyCommand, NametagEdit, OreAnnouncer, PlaceholderAPI, ProtectionStones, ProtocolLib, RewardsLite, SkinsRestorer, TAB, UTitleAuth, Vault, WorldEdit, WorldGuard

### Java Version

java version "20.0.1" 2023-04-18

### Does your issue require a plugin in order to reproduce?

No
