### ISSUE TITLE
How to disable updater?!

### ISSUE THREAD

**Issue by molor** [SkinsRestorer/SkinsRestorerX#337]
I can't disable the updater and remove 10 lines of useless trash from server console.

## How can we reproduce what you got?
config.yml:
```
# Enable or disable the updater.
Updater:
  Enabled: false
  PeriodicChecks: true
```
Then start the server.

**Expected behavior**
Nothing in console about SkinsRestorer updates.

**Screenshots**
![image](https://user-images.githubusercontent.com/19989717/97906754-4317f000-1d55-11eb-94fd-acbe50beaf16.png)

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
This server is running Paper version git-Paper-"4bcebab1" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

* SkinsRestorer: 13.8.5-SNAPSHOT
* Java: 1.8
* Plugin list: LuckPerms, ProtocolLib, SkinsRestorer, WorldEdit, WorldGuard
