### ISSUE TITLE
FR: enable/disable /skins menu

### ISSUE THREAD

**Issue by aljaxus** [SkinsRestorer/SkinsRestorerX#363]
Some SR users have shown the interest in disabling the `/skins` command in order to just use [SkinSystem](https://github.com/riflowth/SkinSystem/).

I suggest the following:
* [ ] add the config option to enable/disable the menu
* [ ] add the option for a custom message being returned in chat on command execute
  * [ ] message handling should also have an enable/disable option 
* [ ] for bungee-mode only
  * [ ] when the plugin(s) on subservers (spigot) load and initialize, they contact the bungee plugin (via plugin messaging) and "ask" if the skins menu should be enabled/disabled

Suggested config format
```yml
...


# GUI settings
Gui:
  # is the /skins command even enabled? Default: true
  Enabled: true
  DisabledGuiMessage:
    # If the GUI menu (/skins) is disabled, should the command still be registred
    # and instead print a message to the player's chat? Default: false
    Enabled: false
    # If the Gui.DisabledGuiMessage.Enabled is true, what should be the message that is printed?
    Message: "SkinsRestorer /skins menu is currently disabled"
  # Custom list for the /skins GUI.
  Custom:
    Enabled: false
    # If Gui.Custom.ShowOnlyCustom is true, the /skins GUI will only
    # show skins from players listed in the Gui.Custom.Names
    ShowOnlyCustom: true
    Names:
      - "xknat"
      - "McLive"


...
```
